manifest:
  version: "0.13"

  remotes:
    - name: alif
      url-base: https://github.com/alifsemi

  projects:
    - name: alif
      url: https://github.com/alifsemi/sdk-alif.git
      revision: 0bb7d893537235fd7eb3dcb03ab8a923b1052884
      path: alif
      import: true

  self:
    path: minimil
# west build -p always -b alif_b1_dk/ab1c1f4m51820hh0/rtss_he samples/hello_world
# west build -b minimil_b1/rtss_he samples/hello_world
# west build -p always -b minimil_b1/rtss_he minimil/samples/hello_world
