manifest:
  version: "0.13"

  remotes:
    - name: alif
      url-base: https://github.com/alifsemi

  projects:
    - name: alif
      url: https://github.com/alifsemi/sdk-alif.git
      revision: 0bb7d893537235fd7eb3dcb03ab8a923b1052884
      path: alif
      import: true

  self:
    path: minimil
